### ISSUE TITLE
Spawn a child process

### ISSUE THREAD

**Issue by blakeembrey** [unional/jspm-config#17]
Currently resolving JSPM configuration relies on mutating the global object. Although unlikely, this means running some code in the primary process that may or may not do things to the current process we don't want it to do. I'd consider spawning a child process that you can kill in case the file is doing something naughty.

**Comment by unional** [comment]
Good point. I'll look into it.

**Comment by unional** [comment]
Do you suggest I use `fork()` and pass data in through env-variable, or there are other options?

**Comment by blakeembrey** [comment]
I think that makes sense. It would be a child process still, so you can spawn it with arguments that you use to read the file, then emit messages back to the host.

**Comment by unional** [comment]
Released 0.2.1 for this

**Comment by unional** [comment]
@blakeembrey it turns out my code doesn't work well. I couldn't get `readJspmConfig.js` next to the source file. It is resolved to `cwd`.
Any suggestion?

**Comment by unional** [comment]
Nevermind. Got it. 🌷
